### ISSUE TITLE
"fmcs.hpp not found" when python setup.py install

### ISSUE THREAD

**Issue by XinboGeng** [FNCS/fncs#8]
xxxxx$ python setup.py install
running install
running build
running build_ext
building 'fncs' extension
creating build
creating build/temp.macosx-10.5-x86_64-2.7
gcc -fno-strict-aliasing -I/xxxx/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include -I/xxxx/anaconda/include/python2.7 -c fncs.cpp -o build/temp.macosx-10.5-x86_64-2.7/fncs.o
fncs.cpp:271:10: fatal error: 'fncs.hpp' file not found
#include "fncs.hpp"
         ^
1 error generated.
error: command 'gcc' failed with exit status 1

**Comment by kdheepak89** [comment]
Run the following command in the directory before trying to install

    `export FNCS_PREFIX=/Users/$USERNAME/FNCS_install`

That will fix the problem

**Comment by jeffdaily** [comment]
To better support FNCS on windows, we have moved away from the compiled Cython extension and instead we recommend using the ctypes, pure python wrapper "fncs.py".  I will update the README.md to reflect this change.
