### ISSUE TITLE
Unable to `import fncs` in python

### ISSUE THREAD

**Issue by kdheepak89** [FNCS/fncs#9]
I get the following error when I try to `import fncs`. I was able to install the cextension with only warning.

    $ python test.py
    Traceback (most recent call last):
      File "test.py", line 4, in <module>
        import fncs
    ImportError: dlopen(/Users/$USERNAME/Documents/GitRepos/fncs/python/fncs.so, 2): Symbol not found: __ZN4fncs10get_valuesERKSs
      Referenced from: /Users/$USERNAME/Documents/GitRepos/fncs/python/fncs.so
      Expected in: dynamic lookup

Do you know what the problem might be?

**Comment by jeffdaily** [comment]
It's likely that the Cython C extension is not up to date with the FNCS C and C++ APIs.  You should use the fncs.py module instead of compiling the C extension.  Sorry for the confusion. Let me know if that works for you.

**Comment by kdheepak89** [comment]
Thanks for the quick reply. I was unfortunately not able to get this to work either. Do you have a working example that you can point me to?

**Comment by kdheepak89** [comment]
I removed the existing `fncs` install (removed the build and egg) and I was able to run `python test.py` but only after changing the `_libname` to  the following. 
 
    _libname = "/Users/$USERNAME/FNCS_install/lib/libfncs.dylib"

with `$USERNAME` modified to your computer's hostname

It looks like `dlopen` is not able to find the correct library file. [Stackoverflow](http://stackoverflow.com/a/22560206).

**Comment by kdheepak89** [comment]
I was able to get around this by trying the following

    export DYLD_FALLBACK_LIBRARY_PATH="/Users/dkrishna/FNCS_install/lib"

But this can possibly cause other unexpected behaviour

**Comment by kdheepak89** [comment]
I was able to get around this by trying the following

    export DYLD_FALLBACK_LIBRARY_PATH="/Users/dkrishna/FNCS_install/lib"

But this can possibly cause other unexpected behaviour [Stackoverflow](http://stackoverflow.com/a/20916003)

**Comment by kdheepak89** [comment]
I was able to get around this by trying the following

    export DYLD_FALLBACK_LIBRARY_PATH="/Users/$USERNAME/FNCS_install/lib"

But this can possibly cause other unexpected behaviour [Stackoverflow](http://stackoverflow.com/a/20916003)
